# Move this to another page, so it reloads itself
title: Alberto Garcia # your name (or website title) here
logo: "/images/Profile2.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>IT & Systems engineer:</b> Python developer and Data Scientist since 2019. Former competitive programming team leader. Taekwondo red belt and Choir Bass. Science and open knowledge supporter. 
theme: jekyll-theme-minimal
google_analytics: G-NS8ZPRJMYC # your Google Analytics tracking ID here
